### ISSUE TITLE
[back-up-firestore-to-storage] Error installing. Some extension resources might not be deployed

### ISSUE THREAD

**Issue by iosmakerov** [htsuruo/firebase-extensions#14]
Hello! I get an error every time I try to install the extension.

; RESOURCE_ERROR at /deployments/firebase-ext-back-up-firestore-to-storage/resources/firebase-ext-back-up-firestore-to-storage-backupTransaction: {"ResourceType":"gcp-types/cloudscheduler-v1:projects.locations.jobs","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Schedule or time zone is invalid.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://cloudscheduler.googleapis.com/v1/projects/forex-trading-lessons/locations/asia-south1/jobs","httpMethod":"POST"}}

<img width="1004" alt="Снимок экрана 2023-07-19 в 22 26 49" src="https://github.com/HTsuruo/firebase-extensions/assets/85504407/07d445b6-42ba-4932-a8aa-b1ad3e0d444c">

**Comment by htsuruo** [comment]
@iosmakerov 

Thanks for report!
It seems that your configuration parameter is correct 👀
I'll check it later.

**Comment by htsuruo** [comment]
@iosmakerov 

Hi, I investigated this issue. And then I recognized that your timezone parameter  `Asia/Munbai` does not exist in standard time zone list. 
For more details, please visit following links.
- [List of tz database time zones - Wikipedia](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).
- [Values for timezone  |  Looker  |  Google Cloud](https://cloud.google.com/looker/docs/reference/param-view-timezone-values)

So, you can set same time zone with `Asia/Calcutta` or `Asia/Kolkata`  instead of `Asia/Munbai`, refer to [here](https://cloud.google.com/looker/docs/reference/param-view-timezone-values#utc0530_chennai_kolkata_mumbai_new_delhi). 

I hope that you can install this extension successfully in your Firebase project 👍

**Comment by iosmakerov** [comment]
Thanks, this helped solve the problem

**Comment by htsuruo** [comment]
@iosmakerov 

You're welcome, feel free to let me know if you have any other issues.
Could you close this issue if solved ?
