### ISSUE TITLE
[back-up-firestore-to-storage] FR: Backup rotation / delete old exports

### ISSUE THREAD

**Issue by danbaechtold** [htsuruo/firebase-extensions#6]
Hi

Thank you very much for your awesome backup extension! :)

Do you plan to add some kind of backup rotation, where older exports are automatically deleted?

Kind regards
Dan

**Comment by htsuruo** [comment]
Hi @danbaechtold , 

Thank you for your request.
It's a good feature request, so I'm plan to implement it. 
I think an approach that numeric optional parameter named like 'Rotation' is added, and then rotates by the number of folders. 
Is it expected feature for you? 
If you have any expected specifications or references, please let me know.

Thanks.

**Comment by danbaechtold** [comment]
Hi @HTsuruo 

Wow that's great to hear :)

The 'Rotation' Parameter (max number of kept versions) is a good option, however I like to keep the first (oldest) backup and then one per month (alwais the 1st day of the month) forever. This is similar to the popular "[Grandfather, Father, Son" backup scheme](https://gomindsight.com/insights/blog/data-backup-schemes/). Some option like that would be fantastic.

Thank you so much.

**Comment by htsuruo** [comment]
@danbaechtold 

Thanks you for reply and references.
I understand your expected behavior for backup. However, I thought about it again and recognized that this issue may be  responsibility of Cloud Storage. 

Cloud Storage supports [Object Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) like setting a Time to Live (TTL) for objects, retaining noncurrent versions of objects etc…

Could you please check if Lifecycle Management can be used to achieve the behavior you are expecting?

**Comment by danbaechtold** [comment]
@HTsuruo Yes, you're right. I didn't think about that, thank you.
